server:
  port: 8888
  servlet:
    context-path: /music

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:33066/music?characterEncoding=UTF-8&&serverTimezone=GMT
    username: root
    password: 1234
  servlet:
    multipart:
      enabled: true
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
file:
  server:
    dir: F:\uploadFile\
    path: /
mybatis:
  mapper-locations: classpath:/mybatis/mappers/*.xml
  type-aliases-package: com.model
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

